name: EasterEventVisantara
version: '1.0.0'
main: me.bintanq.EasterEventVisantara
api-version: '1.21'
authors: [ bintanq ]
description: Easter Event Visantara

depend:
  - MythicMobs
  - MMOItems
  - Multiverse-Core

softdepend:
  - MythicLib

commands:
  easter:
    description: Easter Event admin command.
    usage: /easter <reload|spawn|debug|status|world>
    permission: easter.admin

permissions:
  easter.admin:
    description: Akses semua command /easter.
    default: op